### ISSUE TITLE
My first issue. Yee.

### ISSUE THREAD

**Issue by ox42** [ox42/testrepo#1]
[![CQA](https://carmenqa-dev.cleverbuild.biz/api/shields/info?data=VTJGc2RHVmtYMTlnekxaUGJrOUdBNC9RTWtqZENlOFRjMmpZdFJWOFZSeWdBa1lVeU9oN1R1TVVab0F0ZGl3ZzhFUXNOdVM1TytyLzdGNWV3NmZNNDdZSk1wZlcvcUpoU0c0VGhHTlJLSjF0T21abFJqS1RyM3EzTDNvWGdMdFhWVnVxSTdNL1h6UUNaMnZScWJ6TFRMTmxWUTd0a3NvVS9VdFlMUHhnTDlSR3RQRE03UW1abCs2ckZsOGd2UWcyZEpPNDJWemtEZHV6V3l0YXdsMDljOVJzRGJ6MDZ1T2E1RGdPUWF5NXM1TT0=&parameter=repo)](https://carmenqa-dev.cleverbuild.biz/openticket/TR-93657/1/2509e6d5)
[![CQA](https://carmenqa-dev.cleverbuild.biz/api/shields/info?data=VTJGc2RHVmtYMTlnekxaUGJrOUdBNC9RTWtqZENlOFRjMmpZdFJWOFZSeWdBa1lVeU9oN1R1TVVab0F0ZGl3ZzhFUXNOdVM1TytyLzdGNWV3NmZNNDdZSk1wZlcvcUpoU0c0VGhHTlJLSjF0T21abFJqS1RyM3EzTDNvWGdMdFhWVnVxSTdNL1h6UUNaMnZScWJ6TFRMTmxWUTd0a3NvVS9VdFlMUHhnTDlSR3RQRE03UW1abCs2ckZsOGd2UWcyZEpPNDJWemtEZHV6V3l0YXdsMDljOVJzRGJ6MDZ1T2E1RGdPUWF5NXM1TT0=&parameter=branch)](https://carmenqa-dev.cleverbuild.biz/openticket/TR-93657/1/2509e6d5)

**Comment by carmenqa-buildagent** [comment]
Ticket passed! good ticket. i like it.

**Comment by carmenqa-buildagent** [comment]
Ticket failed! doesnt look good man.

**Comment by carmenqa-buildagent** [comment]
And, I can comment, right?

**Comment by carmenqa-buildagent** [comment]
Ticket passed!
